default: &default
  adapter: mysql
  encoding: utf8
  pool: 5
  username: ubuntu
  password:

development:
  <<: *default
  database: circle_development

test: &test
  <<: *default
  database: circle_test

cucumber:
  <<: *test
