default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: 127.0.0.1

development:
  <<: *default
  database: circle_development

test: &test
  <<: *default
  database: circle_test

cucumber:
  <<: *test
