default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /var/run/mysqld/mysqld.sock
  # in MacOS
  # socket: /tmp/mysql.sock

development:
  <<: *default
  database: streaming_music_development

test:
  <<: *default
  database: streaming_music_test

production:
  <<: *default
  database: streaming_music_production

test:
  <<: *default
  database: streaming_music_test
